### ISSUE TITLE
Problem with expo client

### ISSUE THREAD

**Issue by rtpm** [jamesplease/react-request#145]
Hello, not sure if this is not expo client related. Trying to use Fetch with my expo react native project.
When using <Fetch> in one of my components I get an error below. The problem doesn't appear when turning remoteJS debug on in expo.

I'm using a standard `<Fetch>` with data/failed/fetching props. Importing via `import { Fetch } from 'react-request'` v. 2.0.3

> undefined is not an object (evaluating 'globalObj.AbortSignal')
> 
> <unknown>
>     R:\dev\tres2\app\tres2-proxy\node_modules\react-request\lib\fetch.js:339:33
> loadModuleImplementation
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:213:12
> <unknown>
>     R:\dev\tres2\app\tres2-proxy\node_modules\react-request\lib\index.js:6:13
> loadModuleImplementation
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:213:12
> <unknown>
>     R:\dev\tres2\app\tres2-proxy\components\Invoice.js:6
> loadModuleImplementation
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:213:12
> <unknown>
>     R:\dev\tres2\app\tres2-proxy\App.js:11
> loadModuleImplementation
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:213:12
> <unknown>
>     R:\dev\tres2\app\tres2-proxy\node_modules\expo\AppEntry.js:2
> loadModuleImplementation
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:213:12
> guardedLoadModule
>     R:\dev\tres2\app\tres2-proxy\node_modules\metro\src\lib\polyfills\require.js:140:45
> global code
>     <unknown file>:0

**Comment by jamesplease** [comment]
Hi! I’ve never used React Native, so I’m going to need some help with this one 🙂

**Comment by rtpm** [comment]
Probably something with babel/Node. 

https://github.com/facebook/react-native/issues/14838

Will try to udpate NodeJS to 8 as it seems to solve problem for some.

**Comment by rtpm** [comment]
Could be something with globals not exposed in react-native.

https://github.com/johanneslumpe/react-native-browser-polyfill/blob/master/polyfills/globalself.js

**Comment by jamesplease** [comment]
Agreed @rtpm . I'll add a note to the README about including that polyfill for use in React Native.
