### ISSUE TITLE
Update fetch-dedupe to v3.0.0

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/react-request#149]
For more, see https://github.com/jamesplease/fetch-dedupe/issues/39 and https://github.com/jamesplease/fetch-dedupe/issues/40

//cc @shanecav

**Comment by shanecav** [comment]
👍 

(I think you tagged the wrong Shane here 😆)

**Comment by jamesplease** [comment]
> (I think you tagged the wrong Shane here 😆)

😂...oops

**Comment by jamesplease** [comment]
Closing; resolved in #158 . Will be released in `react-request@3.0.0` sometime soon :v:
