### ISSUE TITLE
rename `doFetch` to `request`?

### ISSUE THREAD

**Issue by ianstormtaylor** [jamesplease/react-request#177]
Realizing that you renamed it from `fetch` in Holen, since that conflicted with the global. But it would be nice to avoid the awkwardness of `doFetch`, by calling it `request` instead. (And it fits with the library name!)

I understand that this would be low priority 😄 but it would make it feel nicer I think!

**Comment by jamesplease** [comment]
Hi @ianstormtaylor ! Thanks for sharing your thoughts here! :v:

I don't feel too strongly about this. I'm not convinced it's worth a breaking API change, but I'd also be OK if other people think it is worth changing.

Future visitors: leave a :+1: or :-1: on the opening post of this issue to cast your vote!

//cc @alansouzati @marlonpp @sprjr

**Comment by andriijas** [comment]
i agree its nicer name but, puh, not sure I want to update my app :)

**Comment by andriijas** [comment]
I feel a way to customize arguments for doFetch is more important

```
export const Login = ({ username, password, ...rest }) => (
  <Authorize
    payload={{ grant_type: "password", username, password }}
    {...rest}
  />
);

<Login>{({doFetch}) => (<Form onSubmit={doFetch} />)}</Login>
```

In this scenario Id like to be able to pass username and password to doFetch

**Comment by jamesplease** [comment]
@andriijas , thanks for sharing your thoughts! Would you want to open a separate issue about your idea to customize arguments for `doFetch`? Let’s keep this issue focused on the name ✌️

**Comment by andriijas** [comment]
Sure, sorry about going out of context.
