### ISSUE TITLE
custom arguments for doFetch

### ISSUE THREAD

**Issue by andriijas** [jamesplease/react-request#181]
```export const Login = ({ username, password, ...rest }) => (
  <Authorize
    payload={{ grant_type: "password", username, password }}
    {...rest}
  />
);

<Login>{({doFetch}) => (<Form onSubmit={doFetch} />)}</Login>
```

Would be nice to be able to pass username and password to doFetch somehow. 
Im currently working around it by using local state for username and password and toggling lazy.

**Comment by jamesplease** [comment]
Hi @andriijas ! In the docs, it describes the usage of `doFetch()`:

> doFetch accepts one argument: options. Any of the fetch() options, such as url, method, and body are valid options. You may also specify a new requestKey if you are manually generating your own keys. This method allows you to customize the request from within the component based on the component's state.

Does this support your use case?

**Comment by andriijas** [comment]
Yes and no.  I try to keep my request components in separate files and dirs from UI components and while it works to alter the options such as url or body I think its nice to hide away the fetch api:s for UI components so that they can just pass whatever data they understand and the request component can keep everything related to how body should be formatted, which method should be used and which URL.

Does this make sense? Its not a deal breaker. I enjoy using react-request 🥂

**Comment by jamesplease** [comment]
That does make sense. I like that same style of organization. I’ll think a little bit about this...there may be something we can do! Let me know if you have any ideas on what changes could be made to support this.

**Comment by andriijas** [comment]
Im going to try to think of something. I dont have any concrete suggestion yet :/

**Comment by jamesplease** [comment]
One idea is as follows:

1. Create a wrapper component that receives your application-specific information, such as `username` and `password`, as props, and transforms that into an HTTP request
2. Within the wrapper component, create a wrapped version of `doFetch` that does the same thing

A very quick (and ugly) implementation demonstrating this is as follows:

```jsx
function FetchWrapper({ children, ...whatevs }) {
  const fetchProps = getFetchProps(whatevs);

  return (
    <Fetch {...fetchProps}>
      ({ doFetch, ...stuff }) => {
        return children({
          ...stuff,
          doFetch(stuff) {
            const arg = getArgFromStuff(stuff);
            return doFetch(arg);
          }
         });
      }
    </Fetch>
  );
}
```

I'm going to close this out for now, but if this doesn't work, or doesn't seem adequate, feel free to let me know and I'd be happy to reopen this issue. Thanks!
