### ISSUE TITLE
Add expiration property

### ISSUE THREAD

**Issue by dcavalcante** [jamesplease/react-request#197]
Set a number of seconds to check in the future if cache has expired

**Comment by jamesplease** [comment]
Hi @dcavalcante , thanks for opening the issue! I've thought about a way to provide your own cache. Then, people can bring in whatever works best for them, and I don't need to try and support every use case in the library.

What do you think of that approach?

**Comment by dcavalcante** [comment]
Agreed! I ended up checking the date from the database in a very specific
way, it's a non issue really :) Thanks for the cool lib and reply
