### ISSUE TITLE
Mock request

### ISSUE THREAD

**Issue by CruelMoney** [jamesplease/react-request#200]
Is there currently a way of mocking requests? 
I'm imagining a mock prop specifying a mocked response.

**Comment by jamesplease** [comment]
Thanks for the issue, @CruelMoney ! I'm thinking you would probably want a lower-level tool for mocking requests, such as [fetch-mock](https://github.com/wheresrhys/fetch-mock). Then, you do not need to think about react-request at all.

Let me know if you run into any issues using fetch-mock with React Request, and I'd be happy to take a look.

**Comment by CruelMoney** [comment]
Thanks James. 
If I mock a request using fetch-mock, will the mock be used in this library?

**Comment by CruelMoney** [comment]
Looks like it, thanks James. 
Amazing library!

**Comment by jamesplease** [comment]
Great, I'm glad that's working for you!
