### ISSUE TITLE
Fetch component not accepting post method.

### ISSUE THREAD

**Issue by Samuelote** [jamesplease/react-request#202]
I think I may have more of a question than an issue, so I do apologize in advance if this is stupid. I'm trying to use the <Fetch/> component to make some calls. When I omit the method prop altogether, it works fine, but if I add the method="post" (or any other method type) it doesn't event attempt to fetch. I am awfully tired so I apologize if this is due to my negligence. 
 
![Screenshot from 2019-10-09 23-53-46](https://user-images.githubusercontent.com/27198821/66542538-195bad80-eaf0-11e9-92d5-e4c47f527007.png)

**Comment by jamesplease** [comment]
No problem, @Samuelote . I understand how this could be confusing. I recommend that you give [this guide](https://github.com/jamesplease/react-request/blob/master/docs/guides/using-the-lazy-prop.md) a read (it is short!), which explains a prop that exists called `lazy`. Let me know if that guide helps you understand what is going on here.

If after reading it you need further help understanding the issue, let me know and I'd be happy to assist more.

**Comment by Samuelote** [comment]
Ah shoot. I figured it was something like that. Thank you so much. I read through it and now understand. Pardon my inattention to detail! Thanks again @jamesplease

**Comment by jamesplease** [comment]
That’s great! I’m glad you were able to figure it out 😁

I’ll close this issue for now, but feel free to let me know if you run into any other issues ✌️
