### ISSUE TITLE
button not showing 

### ISSUE THREAD

**Issue by AbdulRazak-Naeate** [jamesplease/react-request#209]
please I tried this code example below, button not showing

<Fetch
  url="/posts/2"
  method="patch"
  credentials="same-origin"
  headers={{
    'csrf-token': 'myCsrfToken',
  }}
  body={JSON.stringify({ title: 'New post' })}>
  {({ doFetch }) => {
    <button onClick={() => doFetch()}>Update Post</button>;
  }}
</Fetch>

**Comment by jamesplease** [comment]
Perhaps…

```jsx
<Fetch
url="/posts/2"
method="patch"
credentials="same-origin"
headers={{
'csrf-token': 'myCsrfToken',
}}
body={JSON.stringify({ title: 'New post' })}>
{({ doFetch }) => {
<button onClick={() => doFetch()}>Update Post;</button>
}}/>
```

In the future, though, these kinds of questions are better suited for StackOverflow as they aren’t related to this library!
